name: estore
description: Dart command-line application for fetching and printing information from `https://fakestoreapi.com`.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
